language: go
go:
 - 1.8
 - 1.9

install:
 - go get -u github.com/TTWShell/algorithms/data-structure/heap
 - go get -u github.com/TTWShell/algorithms/data-structure/stack
 - go get github.com/stretchr/testify/assert

script:
 - go test -v -cover ./...

branches:
  only:
    - master
