language: go
go:
 - 1.5.4
 - 1.6.3
 - 1.7.5
 - 1.8

install:
 - go get -u github.com/TTWShell/algorithms/heap
 - go get -u github.com/TTWShell/algorithms/stack
 - go get github.com/stretchr/testify/assert

script:
 - go test -v -cover ./...

branches:
  only:
    - master
