version: 2

jobs:
  build:
    docker:
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.8
    working_directory: /go/src/github.com/TTWShell/algorithms

    steps:
      - checkout
      - run:
          name: Run unit tests
          command: |
            go version
            go test -v -cover ./...
